### ISSUE TITLE
app.state program not updated

### ISSUE THREAD

**Issue by axa2** [tsherif/picogl.js#101]
Hello, looking at the source it seems App.state object keeps track of the gl used program.
During DrawCall draw(), the call to currentProgram.bind() checks the appState to avoid calling gl.useProgram if it is already set.
However, during the Program contructor, there is a call to gl.useProgram(null), but the appState is never notified, causing to skip the bind() and failing to draw.
Example:
```javascript
let p = app.createProgram(v, f)
let dc = app.createDrawCall(p, va)
let _ = app.createProgram(v2, f2)
dc.draw() // error
```

**Comment by tsherif** [comment]
Ah, thanks for the heads up. I'll look into this.
