### ISSUE TITLE
DrawCall.draw() and gl.drawElements needs bind index buffer

### ISSUE THREAD

**Issue by axa2** [tsherif/picogl.js#106]
Hello, when calling DrawCall.draw for an indexed VertexArray, gl.drawElements(+) raises a warning because the indexed buffer was not binded. (+ I'm actually using the instanced version; gl.drawElementsInstanced, but I guess the warning would raise also for gl.drawElements)
This is my current workaround:

```javascript
            app.gl.bindBuffer(indexBuffer.binding, indexBuffer.buffer)
            drawcall.draw()
```
Also, the VertexArray fails to be binded during DrawCall.draw(), because VertexArray.bind() checks for appState.vertexArray, but it is not correctly synchronized similarly to issue #101

**Comment by axa2** [comment]
Hello;
```javascript
    let app = PicoGL.createApp(view)
    let drawcall = () => {
        let indices = new Uint16Array([0, 2, 1])
        let va = app.createVertexArray()
            .indexBuffer(app.createIndexBuffer(PicoGL.UNSIGNED_SHORT, 3, indices))
        let prog = app.createProgram(
            `#version 300 es
            void main() { }`
            ,
            `#version 300 es
            precision highp float;
            void main() { }`
        )
        return app.createDrawCall(prog, va)
    }
    let a = drawcall()
    a.draw()
    let _ = drawcall() // comment this to toggle the issue
    a.draw() // GL_INVALID_OPERATION: Must have element array buffer binding
```

**Comment by tsherif** [comment]
Ah, yes I think I see the problem. Actually it looks like the same could happen with any buffer attaching to a vertex array. They bind and unbind the VAO without updating the appState. Should be an easy fix. Thanks for the heads up.
