### ISSUE TITLE
createTexture2D options premultiply (feature request)

### ISSUE THREAD

**Issue by axa2** [tsherif/picogl.js#110]
Hello again!, any chance premultiply could be available when creating a texture from an image?
I'm currently doing this with Javascript and its very slow in comparison to gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL

Thanks for PicoGL, I replaced Three.js with PicoGL in my project and works great.

**Comment by tsherif** [comment]
Thanks you for using it @axa2 :)

This totally makes sense. Should be straightforward to add as a `premultiplyAlpha` option to the Texture and Cubemap constructors, handled similarly to `flipY`.

**Comment by tsherif** [comment]
@axa2 Added a `premultiplyAlpha` option to `Texture` and `Cubemap` in the last release. Can you try it out and verify that it works for you?

**Comment by axa2** [comment]
works perfect! 👍
