### ISSUE TITLE
Texture constructor options.generateMipmaps is ignored

### ISSUE THREAD

**Issue by axa2** [tsherif/picogl.js#115]
Hello!,
It seems the generateMipmaps option is ignored in the Texture constructor.
I think this line:
```javascript
this.mipmaps = (minFilter === CONSTANTS.LINEAR_MIPMAP_NEAREST || minFilter === CONSTANTS.LINEAR_MIPMAP_LINEAR);
```
Should also check options.generateMipmaps.

(just in case; I'm creating a texture from a Float32Array, giving type, internalFormat and generateMipmaps :false)

**Comment by tsherif** [comment]
The `generateMipMaps` option is no longer supported directly. I see that it's still mentioned in the documentation, so I'll fix that.

The relevant line for mipmap generation is this one: https://github.com/tsherif/picogl.js/blob/e1e35e1a89d3f002a31b50bf5b952f273832d39e/src/texture.js#L231

Basically, if you only pass one layer and use a min filter that requires mip maps, the mip maps will automatically be generated. So for your case, passing `minFilter: PicoGL.LINEAR` when creating the texture will prevent generation of mipmaps.
