### ISSUE TITLE
CONSTANTS.WEBGL_INFO.MAX_UNIFORMS is undefined

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [tsherif/picogl.js#117]
Thank you for this wonderful little library. I've been looking through the source code and saw that this constant is not defined anywhere. I'm not sure if it leads to any issues.

https://github.com/tsherif/picogl.js/search?q=max_uniforms&unscoped_q=max_uniforms

My guess is it should `gl.MAX_FRAGMENT_UNIFORM_VECTORS` or `gl.MAX_VERTEX_UNIFORM_VECTORS` depending on if it is a vertex or fragment uniform (as there is often a difference between the two).

Kind regards,

Tim

**Comment by tsherif** [comment]
Ah, whoops! Thanks for the heads-up. Not sure if that got in there as part of a refactor. Won't lead to any functional issues, since those arrays will extend as needed. But part of the design philosophy of PicoGL is to avoid hidden memory allocations, so I'll definitely fix that.
