### ISSUE TITLE
Refactor of VertexArray/VertexBuffer API

### ISSUE THREAD

**Issue by tsherif** [tsherif/picogl.js#121]
I'd like to simplify the interface between the `VertexArray` and `VertexBuffer` classes. Right now, type and size attribute pointer information is stored in the `VertexBuffer`, and the rest is handled by 6 differernt `VertexArray` methods:
- `vertexAttributeBuffer`
- `instanceAttributeBuffer`
- `vertexIntegerAttributeBuffer`
- `instanceIntegerAttributeBuffer`
- `vertexNormalizedAttributeBuffer`
- `instanceNormalizedAttributeBuffer`

Conceptually, it would make sense to move normalized or integer information into the `VertexBuffer` class, in that they describe the data itself. This would make it possible to simplify `VertexArray` to simply two attribute methods: `vertexAttributeBuffer` and `instanceAttributeBuffer`.

Could also be worth it to extend the API to support arbitrary `offset` and `stride` for the attribute pointers.

**Comment by Shimmen** [comment]
I think it sounds like a good idea, as long as it doesn't make the API more complex for the simple tasks. 4 out of 5 times you still only want `vertexAttributeBuffer` and `instanceAttributeBuffer` anyway. The integer/not-integer could maybe be derived from the buffer element type, and normalized could be an optional with a (false) default, so you don't have to think about it.

**Comment by tsherif** [comment]
> as long as it doesn't make the API more complex for the simple tasks

I think it should make things simpler. I'm imagining an API like this, for example, for normalized data:
```js
const normalizedBuffer = app.createVertexBuffer(data, 3, PicoGL.UNSIGNED_BYTE)
.normalized();

vertexArray.vertexAttributeBuffer(0, normalizedBuffer);
```
> integer/not-integer could maybe be derived from the buffer element type

I like this idea. I think this is what people would intuitively expect anyway.

**Comment by tsherif** [comment]
I think I'm going to build this out by allowing `vertexAttributeBuffer` and `instanceAttributeBuffer` to fully specify the pointer with an options object, e.g. 

```js
vertexArray.vertexAttributeBuffer(0, buffer, {offset: 4, stride: 64, size: 4, type: PicoGL.FLOAT});
```

These would override what's defined in the buffer and allow for interleaving. Will probably add a `App.createInterleavedBuffer()` method to support creating a vertex buffer without predefining its structure.
