### ISSUE TITLE
'uniformBlockBases' and 'samplerIndices' are unused

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [tsherif/picogl.js#123]
Hi Tarek,

I just noticed that `uniformBlockBases` is not used in the codebase and it might be unintended that it still is available: https://github.com/tsherif/picogl.js/search?q=uniformBlockBases&unscoped_q=uniformBlockBases

This is also the case for `samplerIndices`: https://github.com/tsherif/picogl.js/search?q=samplerIndices&unscoped_q=samplerIndices

Kind regards,

Tim

**Comment by tsherif** [comment]
Looks like it must be stuff left over from a refactor. Thanks for pointing it out! I'll clean this up for 0.11.0.
