### ISSUE TITLE
Feature request: add support for compressed cubemap textures

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [tsherif/picogl.js#124]
Hi Tarek,

I've noticed [cubemap.js](https://github.com/tsherif/picogl.js/blob/master/src/cubemap.js) lacks support for compressed cubemap textures (`compressedTexSubImage2D)`. Is this is a planned feature? It is for example used in IBL assets generated by [cmgen](https://github.com/google/filament/blob/master/tools/cmgen/src/cmgen.cpp) from the Filament engine (both compressed and non-compressed).

On a side note, was it a conscious choice to move `cubemap` into a separate file and not in [texture.js](https://github.com/tsherif/picogl.js/blob/master/src/texture.js)? It appears that there is quite an overlap between the two.

Kind regards,

Tim

**Comment by tsherif** [comment]
Can definitely do that. I'll probably get that into v0.12.0.

> On a side note, was it a conscious choice to move cubemap into a separate file and not in texture.js? It appears that there is quite an overlap between the two.

As a rule I've just been doing one class per file, just to make it easy to know where to find things, and I found just enough difference in cubemap usage that it was clunky to try consolidate with the other texture types (this will likely be even more true with support for compressed textures).

**Comment by TimvanScherpenzeel** [comment]
Thanks 👍!
