### ISSUE TITLE
Unable to create Int32 texture

### ISSUE THREAD

**Issue by habemus-papadum** [tsherif/picogl.js#132]
Hello, 
I'm having difficulty create an Int32 RGBA texture with the following code:

````
let PicoGL = require("picogl");


const w = 16;
const h = 16;
var canvas = new OffscreenCanvas(w,h);

var app = PicoGL.createApp(canvas)
let channels = 4;

    let data = new Int32Array(w * h * channels);
    for (let y = 0; y < h; y++) {
        for (let x = 0; x < w; x++) {
            const index = (y * w + x) * channels
            data[index] = y * 100 + x;
        }
    }
    
    let t1 = app.createTexture2D(data, w, h, {
        format: PicoGL.RGBA,
        internalFormat: PicoGL.RGBA32I,
        type: PicoGL.INT,
        minFilter: PicoGL.NEAREST,
        magFilter: PicoGL.NEAREST
    });

    console.log(app.gl.getError())
````
the error code is 1282: "invalid operation."  

Do you see anything obvious that I am doing wrong?  Also do you have advice on how I could debug this more efficiently on my own?  (Is there a way to run chrome such that it logs more 
thorough webgl error messages?)

(I'm running latest Chrome on Mac)

thanks!

**Comment by habemus-papadum** [comment]
One thing I noticed is that changing from an OffscreenCanvas to DOM canvas causes error messages to showup in the console log.  

There error message I am getting is:

`[.WebGL-0x7fb7dc01a800]GL ERROR :GL_INVALID_OPERATION : glTexSubImage2D: invalid internalformat/format/type combination GL_RGBA32I/GL_RGBA/GL_INT`

**Comment by habemus-papadum** [comment]
And from that I was able to figure out that the format should be `RGBA_INTEGER`.... cheers!

**Comment by habemus-papadum** [comment]
One small note: `twgl` has pretty good intelligence regarding taking internal format and filling in the proper format and type. It might be worth thinking about adding to `pico`.  Reopening, just so you see this comment, but feel free to close.

**Comment by tsherif** [comment]
Nice :) I'm glad you figured it out. 

PicoGL does have some logic about default texture formats here: https://github.com/tsherif/picogl.js/blob/master/src/constants.js#L666

I just haven't added any for integer types. I'll open a separate issue about this, feel free to submit a PR for it if you'd like.

Also, for usage questions, you should go to the gitter chat room: https://gitter.im/picogl-js/general
There are more people there, so you'll probably get your questions answered more quickly.
