### ISSUE TITLE
Defaults for int texture types

### ISSUE THREAD

**Issue by tsherif** [tsherif/picogl.js#133]
Could add some for INT and UNSIGNED_INT here: https://github.com/tsherif/picogl.js/blob/master/src/constants.js#L666

@habemus-papadum

**Comment by habemus-papadum** [comment]
Actually, I was thinking more  of the reverse direction.   I would like to specify:

````
let t1 = app.createTexture2D(data, w, h, {
        internalFormat: PicoGL.R32I
    });
````

and have picogl infer: 

````
        format: PicoGL.RED_INTEGER,
        type: PicoGL.INT,

````

from the internal format

**Comment by tsherif** [comment]
Hmm... that actually makes sense. Let play around with it a bit.
