### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by Mateiadrielrafael** [tsherif/picogl.js#134]
do you plan on creating some type definitions for this library? Its amazing but i don't like the lack of typescript support (or maybe im just stupid and  don't know where to find the types)

**Comment by tsherif** [comment]
I don't have plans for it as I don't use typescript. What would support look like? We could potentially add it if it isn't too intrusive and wouldn't add maintenance overhead.

**Comment by habemus-papadum** [comment]
Typescript support would involve providing a Typings file, which allows Typescript to safely consume the library and also for IDE's like Webstorm and Atom to provide intelligent assistance (The IDE improvement would be my interest.)  It is probably possible to generate a very useable typings file from the jsdoc (see tsd-jsdoc for instance) -- in which case maintenance overhead would be minimal.  

A slightly more ambitious version of this would involve organizing the enums in constants.js into type safe enums, making it more difficult to pass wrong flags (but this would be a quite a bit of of work, I think, involving rewriting examples, etc)

**Comment by Mateiadrielrafael** [comment]
https://github.com/tsherif/picogl.js/issues/134#issuecomment-483380563

Yes, im using vsc, and ts just thorws me random errors if i dint have declarations. I declared everything i used myself, but just the short names and random things idk what they actually do makes it oretty hard to keep using it like that

The jsdoc to ts thing is a great idea

**Comment by codehz** [comment]
I have wrote a experimental typescript definition: https://gist.github.com/codehz/1dc6ae02dafa547e5a88026b8252cff6
PS: have not tested yet

**Comment by tsherif** [comment]
Experimental support added in #177!
