### ISSUE TITLE
Switch examples to use ES6

### ISSUE THREAD

**Issue by tsherif** [tsherif/picogl.js#135]
Was avoiding this so syntax errors wouldn't prevent the WebGL 2 compatibility message from showing up. But I can avoid this by moving the WebGL 2 check into a separate script.

**Comment by habemus-papadum** [comment]
It would be nice if we could use PicoGL src directly from a browser without building or using bundlers like WebPack/Parcel.  This would involve adding '.js' extensions to each `import from` statement -- I believe that's all that is needed -- a little ugly but I would find this useful.  (My use case would be to install picogl into node_modules, and then just use vanilla html that has an embedded es6 script which imports picogl from the node folder.  This work flow is useful for hacking and also simple debugging into the internals of picogl when learning details)
