### ISSUE TITLE
Empty Vertex Array support removed.

### ISSUE THREAD

**Issue by habemus-papadum** [tsherif/picogl.js#143]
Hi, the changes introduced in #107 seem to have been lost somewhere along the way...

**Comment by tsherif** [comment]
Whoops! Probably in the multi draw update. Will get that back in soon.

**Comment by tsherif** [comment]
@habemus-papadum I've introduced a new method `DrawCall.drawRanges` that lets you explicitly set numElements and numInstances. Would that work for your use case? Currently, you'll need to supply a dummy vertex array for it to work, but we can remove that requirement.

I.e. if this used to work
```js
let va = app.createVertexArray(100, 10);
let dc = app.createDrawCall(program, va);
```

I think this should work in master:
```js
let dc = app.createDrawCall(program, app.createVertexArray())
.drawRanges([0, 100, 10]);
```
And eventually it can become:
```js
let dc = app.createDrawCall(program)
.drawRanges([0, 100, 10]);
```

We should definitely have a test case for this, so it doesn't get lost again.

**Comment by habemus-papadum** [comment]
I have no problem with using drawRanges.  Thanks
