### ISSUE TITLE
app.resize() and devicePixelRatio

### ISSUE THREAD

**Issue by lucasdomanico** [tsherif/picogl.js#151]
Hello, I have a little issue and I can't figure out how to fix it.
Before creating the PicoGL app I call this function;
```javascript
let pixel_ratio = (canvas, w, h) => {
    let ratio = Math.ceil(devicePixelRatio)
    canvas.width = w * ratio
    canvas.height = h * ratio
    canvas.style.width = w + 'px'
    canvas.style.height = h + 'px'
}
// ...
pixel_ratio(canvas, canvas.width, canvas.height)
let app = PicoGL.createApp(canvas)
```
So far so good.
The problem arise when resizing the app:
```javascript
pixel_ratio(canvas, new_width, new_height)
app.resize(canvas.width, canvas.height)
```
I can't get it right.
What is the correct way for handling resize with devicePixelRatio?

Thanks for making PicoGL :)

**Comment by tsherif** [comment]
I haven't played around with `devicePixelRatio`, but picogl isn't concerned with the CSS, so it seems like your code should work. Could you describe more about what's going wrong?

**Comment by lucasdomanico** [comment]
The issue was related to third party code setting the canvas CSS.
PicoGL works great
