### ISSUE TITLE
DrawCall without VertexArray

### ISSUE THREAD

**Issue by lucasdomanico** [tsherif/picogl.js#152]
Hello again. Excuse me if this is a dumb question, but how does `DrawCall` works without providing the `VertexArray`?
I looked into the `DrawCall` docs but I couldn't find how to pass the `VertexArray` (without messing around the `currentVertexArray` property)

**Comment by tsherif** [comment]
You can use the [DrawCall.drawRanges](https://github.com/tsherif/picogl.js/blob/master/src/draw-call.js#L177) method to set up draw parameter without a `VertexArray`.
