### ISSUE TITLE
Texture.data and Texture.bind state

### ISSUE THREAD

**Issue by lucasdomanico** [tsherif/picogl.js#159]
Hello!, I'm chasing a bug where a texture doesn't bind correctly for the drawcall.
I will explain how I fixed it, but if that is not enough I can make an example to reproduce it.

After a call to `Texture.data()` and internally calling `texSubImage2D`, then when calling `DrawCall.draw()`, the Texture fails to be bind.
The first workaround I tried was removing the `if (currentTexture !== this)` statement in `Texture.bind()` source code.
Then I tried a more elegant fix by simply setting `this.currentUnit = -1` at the end of `Texture.data()`.

Does this makes any sense?, If not I will spend time to write an example to reproduce the bug.
Thanks!

**Comment by tsherif** [comment]
Thanks for reporting! This is actually good timing: I just put together a unit testing framework for PicoGL, and you've given me a case to test for!

**Comment by lucasdomanico** [comment]
Cool! Keep up the good work :)

**Comment by tsherif** [comment]
This one was interesting. It's because the active texture wasn't being set for the data update, so the data was being sent to the wrong texture! Fixed in 0.15.2.
