### ISSUE TITLE
readPixels()

### ISSUE THREAD

**Issue by lucasdomanico** [tsherif/picogl.js#168]
Hello!,
Any plans to include a Texture.readPixels method?,
If I understand the docs correctly, there is App.readPixel, but it retrieves a single pixel per call (and only the first color target of the framebuffer I think)
Thanks!

**Comment by tsherif** [comment]
@lucasdomanico Sorry for the late reply. A method like `Texture.readPixels` wouldn't really fit with the philosophy of PicoGL, which is to provide low-level wrappers around actual WebGL operations. There is no WebGL operation to read pixels directly from a texture, so a method like that would involve something like creating a framebuffer object, binding the texture to it, then reading the pixel data.

**Comment by lucasdomanico** [comment]
Hello! You are right, a `Texture.readPixels` is wrong (there is no such WebGL operation for textures)
I think an `App.readPixels` would make sense (there is even an `App.readPixel` API at the moment)
However, I understand that this idea could go against the philosophy of the PicoGL API.
For the record, this is how it can be done with the current API:
```javascript
let w = framebuffer.width
let h = framebuffer.height
let pixels = new  Uint8ClampedArray(w * h * 4)
app.readFramebuffer(framebuffer)
app.gl.readPixels(0, 0, w, h, app.gl.RGBA, app.gl.UNSIGNED_BYTE, pixels)
```
