### ISSUE TITLE
Angle TransformFeedback bug status

### ISSUE THREAD

**Issue by NickPowers43** [tsherif/picogl.js#22]
Hi, I am really liking the library you have made. I am making a port of it to C++ for a project I am working on.

I noticed you have a TODO comment [here](https://github.com/tsherif/picogl.js/blob/master/src/drawcall.js#L189) for a transform feedback bug in Angle. Do you happen to know the status of that bugfix?

**Comment by tsherif** [comment]
Thanks, Nick :) Yes, you can track the bug here: https://bugs.chromium.org/p/angleproject/issues/detail?id=2051

I believe it's fixed in ANGLE now, but hasn't made it's way into Chrome stable yet.
