### ISSUE TITLE
an example of passing a texture in byte/uint8 format?

### ISSUE THREAD

**Issue by mreinstein** [tsherif/picogl.js#28]
@tsherif I'd like to pass a 512x512 uint8array to my fragment shader as a texture. I'm wondering if you could provide a short example on how to do this?

here is what I have in my javascript:
```javascript
var fovData = new Uint8Array(512 * 512)
// code here actually fills the array (omitted for simplicity)
var opts = {
  flipY: false,
  minFilter: PicoGL.NEAREST,
  magFilter: PicoGL.NEAREST,
  wrapS: PicoGL.CLAMP_TO_EDGE,
  wrapT: PicoGL.CLAMP_TO_EDGE,
  format: PicoGL.UNSIGNED_BYTE,
  internalFormat: PicoGL.UNSIGNED_BYTE
}

var texture = app.createTexture2D(fovData, 512, 512, opts)
drawCall.texture('uVisTex', texture)
```

in my fragment shader:

```
precision mediump float;
precision mediump int;
precision mediump usampler2D;

uniform usampler2D uVisTex;

uint refer = texture(uVisTex, vTexCoord);

out vec4 fragColor;

if(refer > 250) {
    fragColor = vec4(color, 0.4);
}
```

I get the typical error messages that happen when trying to operate on a texture incorrectly:

```
localhost/:1 [.Offscreen-For-WebGL-0x7ff8f9a34a00]RENDER WARNING: texture bound to texture unit 1 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.s
```

any help would be greatly appreciated! Also happy to wrap the results up in an example and send as a PR.

**Comment by mreinstein** [comment]
I've also tried this, but it doesn't work either:

```javascript
var opts = {
  flipY: false,
  minFilter: PicoGL.NEAREST,
  magFilter: PicoGL.NEAREST,
  wrapS: PicoGL.CLAMP_TO_EDGE,
  wrapT: PicoGL.CLAMP_TO_EDGE,
  format: PicoGL.ALPHA,
  internalFormat: PicoGL.ALPHA
}
```

```
precision mediump float;

uniform sampler2D uVisTex;

vec4 refer = texture(uVisTex, vTexCoord);

if(refer.a > 0.8) {
    fragColor = vec4(color, 0.4);
}
```

basically I'm trying to send just one byte per pixel, rather than rgba because I only need 1 channel and want to reduce the cpu -> gpu bandwidth.

**Comment by tsherif** [comment]
For a one-channel, single-byte texture, you'll want to use the combination of `PicoGL.RED`/`PicoGL.R8`/`PicoGL.UNSIGNED_BYTE` for format/internalFormat/type. So you're opts should look something like this:
```JavaScript
var opts = {
  flipY: false,
  minFilter: PicoGL.NEAREST,
  magFilter: PicoGL.NEAREST,
  wrapS: PicoGL.CLAMP_TO_EDGE,
  wrapT: PicoGL.CLAMP_TO_EDGE,
  type: PicoGL.UNSIGNED_BYTE,
  format: PicoGL.RED,
  internalFormat: PicoGL.R8
}
```
And then you'll find the values in the red channel of the texture sample (`refer.r`). 

For the all the valid combinations, check out the format tables here: https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glTexStorage2D.xhtml

**Comment by mreinstein** [comment]
thanks!
