### ISSUE TITLE
style change proposals

### ISSUE THREAD

**Issue by mreinstein** [tsherif/picogl.js#31]
@tsherif let me preface this by saying these ideas are in the realm of very trivial style changes. If you don't want to pursue them no big deal. That said, would you be open to removing unnecessary semicolon use and switching to single quotes? e.g.,

```javascript
    this.canvas = canvas
    this.gl = canvas.getContext('webgl2', contextAttributes)
```

looks slightly cleaner than:
```javascript
    this.canvas = canvas;
    this.gl = canvas.getContext("webgl2", contextAttributes);
```

**Comment by tsherif** [comment]
My preference is for double-quotes and semi-colons.
