### ISSUE TITLE
Occlusion culling example

### ISSUE THREAD

**Issue by tsherif** [tsherif/picogl.js#33]
Port Shrek's new [occlusion culling example](https://tsherif.github.io/webgl2examples/occlusion.html) to PicoGL. This will require a fair bit of new functionality:
- Occlusion queries
- Ability to loop through draw calls manually (so you can draw the bounding box, then decide if you want to draw the sphere)
- Control of viewport
- Scissor test

**Comment by Shimmen** [comment]
Some ideas:

- It would be nice to have some generic gl query support.
- As an alternative to setting draw calls and calling draw, it would be good to have a function like `drawImmediate` which takes one draw call as a parameter and performs is directly.

**Comment by tsherif** [comment]
Both those ideas make sense to me. For the second one, I'm thinking of just making DrawCall.draw() easier to use directly.
