### ISSUE TITLE
Support for float VertexBuffer with TypedArray other than Float32Array

### ISSUE THREAD

**Issue by kchapelier** [tsherif/picogl.js#54]
Currently `App.createVertexBuffer`'s `type` argument is used to decide whether to use `vertexAttribPointer ` or `vertexAttribIPointer` when defining a VertexArray attribute but it is also used to set the data type and the stride of the attribute.

https://github.com/tsherif/picogl.js/blob/master/src/vertex-array.js#L129

This means it is not possible to set a non-integer attribute with a Int8Array, because that would require setting its type to BYTE which would trigger the use of `vertexAttribIPointer`.

Using a Int8Array with `type` set to PicoGL.BYTE, for an attribute defined as a float in the shader triggers `GL ERROR :GL_INVALID_OPERATION : glDrawElements: vertexAttrib function must match shader attrib type`.

And using a Int8Array with type set to PicoGL.FLOAT triggers `GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute X`.

Decoupling the attribute type and the data type (actual ArrayBufferView type) would allow more flexibility. For example, with voxel-based meshes it is possible to use 75% less memory on normals and UVs by using Int8Array instead of Float32Array. Likewise an SVG logo converted to a flat 3D mesh could use a Int8Array for its normals.

**PS: Thanks for your work on this library, it's great !**

**Comment by tsherif** [comment]
Thanks, @kchapelier :)

You're absolutely right. What I'll do is implement an example like this old [mesh compression demo](https://tsherif.github.io/mesh-compression-examples/quantize-oct.html), which passes ints as float attributes, both normalized and unnormalized. I'll build the new features around that to make sure everything works properly.
