### ISSUE TITLE
Proposal doc update for python >=3

### ISSUE THREAD

**Issue by tolkanabroski** [tsherif/picogl.js#65]
https://tsherif.wordpress.com/2017/07/26/webgl-2-development-with-picogl-js-part-1-the-triangle/

SimpleHTTPServer is deprecated

https://docs.python.org/release/3.0.1/library/http.server.html
> python -m http.server

System: Windows 10 x64
Python 3.6.2

**Comment by tsherif** [comment]
Ah, good to know. Will do, thanks.
