### ISSUE TITLE
Remove workarounds for ANGLE transform feedback bug

### ISSUE THREAD

**Issue by sjfricke** [tsherif/picogl.js#85]
This has been fixed in ANGLE: https://bugs.chromium.org/p/angleproject/issues/detail?id=2051
But the latest version of ANGLE hasn't been released in Firefox stable yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1425422

Remove these workarounds once Firefox is updated: 
https://github.com/tsherif/picogl.js/blob/eb7d181d1a630aa0de266d68a2ad6580b4d8b6d8/src/transform-feedback.js#L41
https://github.com/tsherif/picogl.js/blob/eb7d181d1a630aa0de266d68a2ad6580b4d8b6d8/src/draw-call.js#L175

**Comment by tsherif** [comment]
Good call. I've updated the text with all the relevant information

**Comment by tsherif** [comment]
Checked and the bug is fixed in Firefox. Workarounds can be removed now.
