### ISSUE TITLE
Inconsistently returning "this" object

### ISSUE THREAD

**Issue by sjfricke** [tsherif/picogl.js#89]
I have noticed that there is no consistent returning of `this`

Some classes like [VertexArray](https://github.com/tsherif/picogl.js/blob/master/src/vertex-array.js) return it with every method and other like [Program](https://github.com/tsherif/picogl.js/blob/master/src/program.js) don't at all

I can PR all methods to return `this`, but not sure if there is a reason to not return it for some cases

**Comment by tsherif** [comment]
@sjfricke Yeah this is a good idea. Feel free to put together a PR. I think all methods should return `this`. The missing ones are likely just that I missed them. DrawCall.draw is another one where I noted the return missing.
