### ISSUE TITLE
Deferred lighting broken in chrome

### ISSUE THREAD

**Issue by sjfricke** [tsherif/picogl.js#90]
Just noticed that both Bloom and Deferred Lighting are both broken with chorme. The non-first added lights start flickering, this is shown by swapping the order out in Deferred lighting and the first light works while the rest start flickering.

I tested it on Firefox, Chrome Canary, and Mobile Chrome and it works fine on those. I also tried reverting to PicoJs V.0.6 and had no luck so makes me think its a chrome specific bug

I have never done anything in deferred lighting so not really sure where to start looking.

Specs:
Chrome/63.0.3239.84
Windows NT 10.0.16299
ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
1.4 (ANGLE 2.1.0.9095f2b44801)
OpenGL ES 3.0 (ANGLE 2.1.0.9095f2b44801)

**Comment by Shimmen** [comment]
Can't reproduce on Chrome Version 63.0.3239.132 Windows 10. Everything looks fine. Still bad for you?

**Comment by sjfricke** [comment]
Everything works now, might have been a chrome bug that was fixed, on Chrome 64 now anyways
