### ISSUE TITLE
Function for validating framebuffers

### ISSUE THREAD

**Issue by Shimmen** [tsherif/picogl.js#93]
It would be convenient to have some function for validating that a framebuffer is valid, i.e. a wrapper around [`glCheckFramebufferStatus`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/checkFramebufferStatus).

I was implementing some basic shadow mapping today and had a framebuffer with a `GL_R16F` color buffer. Turns out it wasn't a valid setup and I got errors when trying to render to it, but for some reason very inconsistently (every other Ctrl-R it actually did work). Validating the framebuffer after construction always reported an error though.

Of course we shouldn't build features on inconsistent behaviors like that, but I still think it's very comfortable to be able to validate a framebuffer in "assembly time" and it's something I usually always do.

I propose that we add a function `getStatus`, or if we want a lighter API `isValid`, to the `Framebuffer` class.

**Comment by tsherif** [comment]
Great idea. I think I'd prefer a `getStatus` method as it's more flexible. And it would be easy enough for the application to write a function that returns `fb.getStatus() === PicoGL.FRAMEBUFFER_COMPLETE.`

While we're on the topic, I'm wondering if there are any other objects we'd want to have GL getter methods on. You can get some handy information for debugging, for example, from `getActiveUniformBlockParameter` and `getBufferParameter`.

**Comment by Shimmen** [comment]
I can't think of any specific thing I would use right now, but yeah sure, getters for that kind of stuff can always be helpful.
