### ISSUE TITLE
Cubemap documentation issues

### ISSUE THREAD

**Issue by Shimmen** [tsherif/picogl.js#94]
There are several functions in the API that accepts both `Cubemap`s and `Texture`s, but in most places only `Texture` is documented as a valid parameter type. Examples are `DrawCall.texture`, `Framebuffer.colorTarget` and `Framebuffer.depthTarget`.

There are also some missing details around creating cubemaps, specifically for cubemaps without any input textures.

**Comment by tsherif** [comment]
Fixed by #95
