### ISSUE TITLE
numColorTargets of Framebuffer can be made invalid

### ISSUE THREAD

**Issue by Shimmen** [tsherif/picogl.js#97]
Every time `Framebuffer.colorTarget(...)` is called `numColorTargets` is incremented:

https://github.com/tsherif/picogl.js/blob/74542e3abe00d1e716addbd5012288599620be7b/src/framebuffer.js#L66-L87

If you do something like this, though, it will break:
```javascript
framebuffer.colorTarget(0, texture);
framebuffer.colorTarget(0, someOtherTexture);
```

Or the case that I stumbled upon with texture arrays:
```javascript
framebuffer.colorTarget(0, texture, 0);
framebuffer.colorTarget(0, texture, 1);
```

In both cases `numColorTargets` would be set to `2` but only one texture is ever attached at one time. In these cases an exception would occur when such a framebuffer is resized and it tries to resize the color textures (i.e. out of bounds):
https://github.com/tsherif/picogl.js/blob/74542e3abe00d1e716addbd5012288599620be7b/src/framebuffer.js#L129

**Comment by tsherif** [comment]
Ah yeah, of course! Oversight on my part. I'm out of town until next week, but I'll look into this when I get back.
